backend:
  name: git-gateway
  branch: main

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"
i18n:
  structure: multiple_files
  locales: [en, ar]
  default_locale: en
permalinks:
  news: /:year/:month/:title/
taxonomies:
  news/tag: news/tags
  news/category: news/categories


collections:
   i18n: true
    files:
      - file: ["src/pages/about.en.md","src/pages/about.ar.md"]
        label: "About Page"
        name: "about"
        i18n: true
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page", i18n: duplicate}
          - {label: Title, name: title, widget: string, i18n: true}
          - {label: Heading, name: heading, widget: string, i18n: true}
          - {label: "Body", name: "body", widget: "markdown", i18n: true}